language: ruby
sudo: true
before_install:
  - sudo apt-get install libpotrace-dev
addons:
  code_climate:
    repo_token: 180e7e03547123015fff4d53f2f0794e557cd225259733803c4841ab1001c425
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.9
  - 2.0.0
