language: ruby
sudo: true
before_install:
  - sudo apt-get install libpotrace-dev
addons:
  code_climate:
    repo_token: 180e7e03547123015fff4d53f2f0794e557cd225259733803c4841ab1001c425
rvm:
  - 2.2.3
  - 2.1.5
  - 2.1.1
  - 2.1.0
  - 2.0.0
